# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chunk_builder <- function(xx, chunk_num, chunk_size) {
    .Call('_gruph_chunk_builder', PACKAGE = 'gruph', xx, chunk_num, chunk_size)
}

chunk_builder_gaussian <- function(xx, chunk_num, chunk_size) {
    .Call('_gruph_chunk_builder_gaussian', PACKAGE = 'gruph', xx, chunk_num, chunk_size)
}

fl_dginit <- function(xx, yy, queue_size, penalty, verbose) {
    .Call('_gruph_fl_dginit', PACKAGE = 'gruph', xx, yy, queue_size, penalty, verbose)
}

fl_linear <- function(xx, yy, queue_size, penalty, verbose) {
    .Call('_gruph_fl_linear', PACKAGE = 'gruph', xx, yy, queue_size, penalty, verbose)
}

full_dinit <- function(xx, offset) {
    .Call('_gruph_full_dinit', PACKAGE = 'gruph', xx, offset)
}

full_linear <- function(xx, yy) {
    .Call('_gruph_full_linear', PACKAGE = 'gruph', xx, yy)
}

full_linear_gaussian <- function(xx, yy) {
    .Call('_gruph_full_linear_gaussian', PACKAGE = 'gruph', xx, yy)
}

max_forest <- function(x, num_nodes, penalty) {
    .Call('_gruph_max_forest', PACKAGE = 'gruph', x, num_nodes, penalty)
}

cinit <- function(m, lambda, silent) {
    .Call('_gruph_cinit', PACKAGE = 'gruph', m, lambda, silent)
}

dinit <- function(m, lambda, silent) {
    .Call('_gruph_dinit', PACKAGE = 'gruph', m, lambda, silent)
}

dginit <- function(m, lambda, silent) {
    .Call('_gruph_dginit', PACKAGE = 'gruph', m, lambda, silent)
}

minit <- function(x, y, lambda, silent) {
    .Call('_gruph_minit', PACKAGE = 'gruph', x, y, lambda, silent)
}

dminit <- function(x, y, lambda, silent) {
    .Call('_gruph_dminit', PACKAGE = 'gruph', x, y, lambda, silent)
}

sgn_info_mat <- function(cont, dis) {
    .Call('_gruph_sgn_info_mat', PACKAGE = 'gruph', cont, dis)
}

cpp_sd <- function(px) {
    .Call('_gruph_cpp_sd', PACKAGE = 'gruph', px)
}

cpp_cor <- function(px, py) {
    .Call('_gruph_cpp_cor', PACKAGE = 'gruph', px, py)
}

